tradecloud/tradecloud-docs-api-v2

authentication.md

https://tradecloud.atlassian.net/browse/TC-4734
This PR ......
Can be viewed here: https://app.gitbook.com/@tradecloud/s/api/v/TC-4734-refresh-token/authentication

TC-4734 Verify the refresh token is working and document it.

---

README.md
SUMMARY.md
authentication.md
company/README.md
company/connect-to-company.md
company/get.md
company/list-connected-companies.md
company/overview.md
company/search-new-companies.md
company/update.md

https://tradecloud.atlassian.net/browse/TC-5233
This PR create company api manual

Tc 5233 company api v2 docs

---

SUMMARY.md
order/supplier/propose-changes.md
order/supplier/reject.md

https://tradecloud.atlassian.net/browse/TC-5248
This PR creates api docs for reject order and propose order changes

[TC-5248] supplier order process api v2 docs

---

security/authentication.md

https://tradecloud.atlassian.net/browse/TC-6370
This PR contains suggestions about how to make the docs a little cleaner (including markdown code cleanup)
Can be reviewed here: https://app.gitbook.com/@tradecloud/s/api/v/TC-6370-authentication-docs-review/security/authentication

[TC-6370] Review and polish authentication docs

---

buyer/issue/README.md
buyer/issue/attach-document.md
supplier/send-order-response/README.md
supplier/send-order-response/attach-document.md

https://tradecloud.atlassian.net/browse/TC-6592
This PR makes companyId optional in the API manual

[TC-6592] change companyId 4x

---

SUMMARY.md
buyer/issue/README.md
buyer/issue/attach-document-api.md
buyer/issue/attach-document.md

https://tradecloud.atlassian.net/browse/TC-6712
This PR updates attach documents docs.
Can be seen on this [Gitbook page](https://app.gitbook.com/@tradecloud/s/api/v/TC-6712-attach-documents/buyer/issue/attach-document)

[TC-6712] - update attach documents docs

---

SUMMARY.md
api/rules.md
api/standards.md
buyer/approve-proposal.md
buyer/issue/attach-document-api.md
buyer/issue/attach-document.md
buyer/issue/no-delivery-expected.md
security/media-types.md
supplier/send-order-response/attach-document.md

https://tradecloud.atlassian.net/browse/TC-5330
This PR adds supported media types and file extensions
according to object-storage/src/main/scala/com/tradecloud1/objectstorage/api/FilesValidator.scala
https://tradecloud.gitbook.io/api/v/TC-5330-supported-media-types/security/media-types

[TC-5330] Add supported media types and file extensions

---

security/authentication.md

https://tradecloud.atlassian.net/browse/TC-6838
This PR adds object-storage basic authentication to the authentication page
https://app.gitbook.com/@tradecloud/s/api/v/TC-6838-add-object-storage-basic-authentication/security/authentication

[TC-6838] Add object-storage basic authentication

---

.gitbook/assets/Tradecloud-Demo.postman_collection.json
.gitbook/assets/tradecloud-demo.postman_collection.json
api/requests.md

https://tradecloud.atlassian.net/browse/TC-6789
This PR includes additional docs for sending SCSN XML to the `sci-connector`
Can be reviewed here: https://app.gitbook.com/@tradecloud/s/api/v/TC-6789-sci-request-example/api/requests

[TC-6789] Update Postman collection with SCSN example

---

buyer/receive/README.md
supplier/overview.md
supplier/receive/README.md

Story https://tradecloud.atlassian.net/browse/TC-7064
Sub task https://tradecloud.atlassian.net/browse/TC-7066
This PR adds ETD to the delivery line in the order line delivery schedule.
https://app.gitbook.com/@tradecloud/s/api/v/TC-7064-add-delivery-line-etd/buyer/receive#logistics-fields
https://app.gitbook.com/@tradecloud/s/api/v/TC-7064-add-delivery-line-etd/supplier/receive#logistics-fields

[TC-7064] [TC-7159] Add ETD

---

buyer/indicators.md
buyer/issue/README.md

story https://tradecloud.atlassian.net/browse/TC-5667
sub task https://tradecloud.atlassian.net/browse/TC-7161
This PR adds Shipped to incoming deliverySchedule.status in the API manual
https://app.gitbook.com/@tradecloud/s/api/v/TC-5667-add-incoming-delivery-line-shipped/buyer/issue#requested-planned-delivery-schedule

[TC-5667] Add Shipped to incoming deliverySchedule.status

---

security/authorization.md

https://tradecloud.atlassian.net/browse/TC-7000
This PR renames Tradecloud1 to API v2 on Sjors' request
https://app.gitbook.com/@tradecloud/s/api/v/TC-7000-rename-tradecloud1-to-apiv2/security/authorization

[TC-7000]  Rename Tradecloud1 to API v2

---

api/rules.md

https://tradecloud.atlassian.net/browse/TC-7427
This PR adds client retry strategies to the rules.

[TC-7427] Add retry strategies

---

buyer/receive-goods.md

https://tradecloud.atlassian.net/browse/TC-7230
This PR adds delivery eventst to the receive goods page.

[TC-7230] Add delivery events

---

buyer/issue/attach-document-api.md
buyer/issue/attach-document.md

https://tradecloud.atlassian.net/browse/TC-7202
This PR
- It is missing that business logic that when a document comes in with the same `code` as an already existing document within that order or order line, that then the existing document will be overwritten with the new document. 
- also the document embed and document attach flows should be explained (in which order you should do stuff) , as GAC / Eichholtz did not understand it correctly. They tried to attach documents before sending orders.

[TC-7202] Improve document attaching

---

buyer/issue/README.md
supplier/receive/README.md
supplier/send-order-response/README.md

https://tradecloud.atlassian.net/browse/TC-7375
This PR
- adds order type
- some improvements

[TC-7375] Add order type

---

README.md
api/compatibility.md
order/README.md
security/documents.md
shipment/README.md
shipment/buyer/receive-shipment-event.md
shipment/supplier/send-despatch-advice.md

https://tradecloud.atlassian.net/browse/TC-7524
This PR additional fixes after merge.

[TC-7524] Fixes

---

shipment/buyer/README.md
shipment/buyer/receive-shipment-event.md
shipment/supplier/README.md
shipment/supplier/send-despatch-advice.md

https://tradecloud.atlassian.net/browse/TC-7524
This PR ......

[TC-7524] Fix pages overviews

---

api/environments.md

https://tradecloud.atlassian.net/browse/TC-7166
This PR add egress ip addresses for white listing by customers
- requested by Moba
- already used by Voortman and others

[TC-7166] Add egress ip addresses for white listing by customers

---

order/buyer/issue/README.md
order/supplier/receive/README.md

https://tradecloud.atlassian.net/browse/TC-7729
This PR adds 2 small fixes for a broken link and broken layout, following https://github.com/tradecloud/tradecloud-docs-api-v2/pull/48

[TC-7729] Fix broken link and layout

---

SUMMARY.md
order/buyer/overview.md
order/buyer/receive/README.md
order/buyer/receive/download-document.md
order/supplier/receive/README.md
shipment/buyer/overview.md
shipment/buyer/receive/README.md
shipment/buyer/receive/download-document.md

https://tradecloud.atlassian.net/browse/TC-7804
This PR adds shipments documents to the API manual.

[TC-7804] Add shipments documents

---

api/environments.md

https://tradecloud.atlassian.net/browse/TC-8236

feat: [TC-8236] Change Tradecloud1 source IP for `acceptance` environment

---

order/buyer/issue/README.md
order/buyer/receive/README.md
order/supplier/receive/README.md
order/supplier/send-order-response/README.md

https://app.intercom.com/a/inbox/nel1ptj2/inbox/shared/all/conversation/106384000085140
This PR adds all missing prices fields.

[TC-7777] Add all prices fields

---

order/buyer/issue/README.md

https://tradecloud.atlassian.net/browse/TC-8848
Review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/RUhXQj5vjcIlPFWul2ay/processes/order/buyer/issue#order
This PR adds company parties to buyer order issue

[TC-8848] Add order company parties

---

forecast/slimstock.md

https://tradecloud.atlassian.net/browse/TC-8867
This PR contains the docs for the updated Slimstock API.

docs(slimstock): [TC-8867] Update Slimstock API docs

---

SUMMARY.md
order/buyer/issue/README.md
order/buyer/issue/delivery-schedule.md
order/buyer/update.md

https://tradecloud.atlassian.net/browse/TC-8846
Please review https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/0F5zcWdcGUZudEj4gIGO/processes/order/buyer/issue/delivery-schedule#simple-delivery-schedule
This PR add buyer simple delivery schedule api
Webhook is out of scope

[TC-8846] Add buyer simple delivery schedule api

---

api/webhook-vs-polling.md
order/buyer/receive/README.md
order/supplier/receive/README.md
shipment/buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8978
This PR adds shipment polling to the API manial
Please review https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/MifRCHBvioSaeHd6eVnH/introduction/api/webhook-vs-polling

[TC-8978] Add shipment polling

---

shipment/buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8527 story
https://tradecloud.atlassian.net/browse/TC-9086 sub task
Please review https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/YwgnGvhasacQsZBElFKE/processes/shipment/buyer/receive
This PR adds load carriers to the shipment API manual

[TC-8527] [TC-9086] Add load carriers

---

shipment/buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8549 story
https://tradecloud.atlassian.net/browse/TC-9089 sub task
This PR adds Issue a shipment to the API manual

[TC-8549] [TC-9089] Issue a shipment

---

shipment/buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8551 story
https://tradecloud.atlassian.net/browse/TC-9090 sub task
This PR adds shipment Approved event and status

[TC-8551] [TC-9090] Add shipment Approved event and status

---

shipment/buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8552 story
https://tradecloud.atlassian.net/browse/TC-9098 sub task
Review https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/L7WRJ0Taz9CulaengHU2/processes/shipment/buyer/receive
This PR adds shipment Rejected event and status

[TC-8552] [TC-9098] Add shipment Rejected event and status

---

order/buyer/issue/indicators.md

https://tradecloud.atlassian.net/browse/TC-9040
This PR adds the `confirmed` indicator to the order/buyer/issue/indicators page
https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/myzMNlOnceSczU7IHbdU/processes/order/buyer/issue/indicators

[TC-9040] [TC-9192] Add Confirmed indicator

---

checklist.md
order/buyer/README.md
order/buyer/issue/delivery-schedule.md

https://tradecloud.atlassian.net/browse/TC-9206
This PR contains suggestions for #73

docs: [TC-9206] Checklist suggestions

---

README.md
SUMMARY.md
api/compatibility.md
api/rules.md
api/standards.md
checklist.md
order/buyer/README.md
order/buyer/issue/README.md
order/buyer/issue/delivery-schedule.md
order/buyer/receive/README.md
order/buyer/receive/delivery-schedule.md
support.md

https://tradecloud.atlassian.net/browse/TC-9206
Review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/3XGRh5PZXStpDTAJliLS/introduction/readme/checklist
This PR
- adds a checklist which contains important info and decisions to consider before start building an API integration with Tradecloud
- extends standards with TLS 1.3 and XML
- adds a delivery schedule page at the buyer receiver side
- small improvements and fixes

[TC-9206] Add API integration checklist

---

order/buyer/cancel.md
order/buyer/complete.md
order/buyer/issue/README.md
order/buyer/issue/delivery-schedule.md
order/buyer/issue/indicators.md
order/buyer/receive-goods.md
order/buyer/update.md

https://tradecloud.atlassian.net/browse/TC-9120
Review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/igW0jrDwg3usb2btu4H2/processes/order/buyer/update
This PR adds actual delivery

[TC-9120] Add actual delivery

---

api/polling/README.md

https://tradecloud.atlassian.net/browse/TC-9650
This PR replace the reference to `shipment/search` with `shipment/poll` for docs related to polling.

docs: [TC-9650] Refer to shipment polling endpoint

---

api/polling/README.md
security/authentication.md

https://tradecloud.atlassian.net/browse/TC-9655
This PR refers to the order-search poll endpoint instead of the deprecated order-search endpoint for polling.

[TC-9655] Refer to order-search poll endpoint
