tradecloud/tradecloud-docs-api-v2

buyer/issue/README.md

https://tradecloud.atlassian.net/browse/TC-5716
This PR creates and uses a separate Price model only to be used by the order integration API.

[TC-5716] Make priceInBaseCurrency mandatory in order integration API

---

buyer/issue/README.md

https://tradecloud.atlassian.net/browse/TC-5597
This PR adds
- [TC-5597] Add labels to order and line 
- [TC-6344] Add row to line
to the buyer issue order API manual page
For review: https://tradecloud.gitbook.io/api/~/revisions/-MI4bt8PGhHa0ljTE0b5/v/TC-5597-labels/buyer/issue
[TC-5597]: https://tradecloud.atlassian.net/browse/TC-5597
[TC-6344]: https://tradecloud.atlassian.net/browse/TC-6344

[TC-5597] Add labels to order and line [TC-6344] Add row to line

---

buyer/approve-proposal.md
buyer/cancel.md
buyer/complete.md
buyer/indicators.md
buyer/receive-goods.md
buyer/ship-goods.md

https://tradecloud.atlassian.net/browse/TC-6430
This PR adds the orders indicators API resource to the API manual
https://tradecloud.gitbook.io/api/~/revisions/-MO67_Ge1Vm7StlRI34L/v/TC-6630-add-order-indicators/

[TC-6430] Add orders indicators API

---

api/rules.md
buyer/issue/README.md
buyer/update.md
supplier/send-order-response/README.md

https://tradecloud.atlassian.net/browse/TC-6710
This PR adds a rule and warnings to only send new or changes lines in an order or order response
https://tradecloud.gitbook.io/api/~/revisions/-MSKEhpRW36ToItjcyL5/v/TC-6710-send-only-new-or-changed-lines/api/rules#the-order-or-order-response-should-only-contain-new-or-changed-lines
https://tradecloud.gitbook.io/api/~/revisions/-MSKEhpRW36ToItjcyL5/v/TC-6710-send-only-new-or-changed-lines/buyer/issue
https://tradecloud.gitbook.io/api/~/revisions/-MSKEhpRW36ToItjcyL5/v/TC-6710-send-only-new-or-changed-lines/supplier/send-order-response

[TC-6710] Send only new or changed lines

---

api/rules.md
buyer/issue/README.md

https://tradecloud.atlassian.net/browse/TC-6728?focusedCommentId=58371
This PR adds the rule and warning that identifiers must not contain whitespace characters
https://tradecloud.gitbook.io/api/~/revisions/-MSIz_yDGFP14FIjGMAC/v/TC-6728-ids-not-contain-whitespaces/api/rules#identifiers-must-not-contain-whitespace-characters
https://tradecloud.gitbook.io/api/~/revisions/-MSIz_yDGFP14FIjGMAC/v/TC-6728-ids-not-contain-whitespaces/buyer/issue#order

[TC-6728] Ids must not contain whitespace characters

---

api/environments.md

https://tradecloud.atlassian.net/browse/TC-6807
https://tradecloud.gitbook.io/api/v/TC-6807-prod-env-availability/api/environments
This PR amends production availability to 99,5% during 9:00 to 18:00 CE(S)T on working days.

[TC-6807] Amend prod env availability

---

buyer/cancel.md
buyer/indicators.md
buyer/update.md

Story: https://tradecloud.atlassian.net/browse/TC-6957
Sub task: https://tradecloud.atlassian.net/browse/TC-7119
This PR adds `cancelLineWhenMissing` indicator to the API manual.
https://app.gitbook.com/@tradecloud/s/api/v/TC-7119-cancelLineWhenMissing-indicator/buyer/cancel#cancelling-by-resending-the-order-without-the-cancelled-line-using-the-order-api

[TC-6957] [TC-7119] Add `cancelLineWhenMissing` indicator

---

SUMMARY.md
buyer/issue/README.md
buyer/issue/no-delivery-expected.md
buyer/issue/propose-when-accepted.md
buyer/update.md

Story https://tradecloud.atlassian.net/browse/TC-6974
Sub task https://tradecloud.atlassian.net/browse/TC-7158
This PR adds 
- the "Propose when accepted" feature to the API manual
https://tradecloud.gitbook.io/api/v/TC-7158-propose-when-accepted/buyer/issue#other-line-fields
https://tradecloud.gitbook.io/api/v/TC-7158-propose-when-accepted/buyer/issue/propose-when-accepted
- moves basic logistics from the `order update` to the `order issue` pages, as the delivery live status may be set already when issuing the order
https://tradecloud.gitbook.io/api/v/TC-7158-propose-when-accepted/buyer/issue#requested-planned-delivery-schedule

[TC-7158] Add propose when accepted

---

buyer/issue/README.md
buyer/receive/README.md

https://tradecloud.atlassian.net/browse/TC-7159
This PR gives an additional clarification about the mandatory delivery line position
https://tradecloud.gitbook.io/api/v/TC-7159-delivery-schedule-position-mandatory/buyer/issue#requested-planned-delivery-schedule
https://tradecloud.gitbook.io/api/v/TC-7159-delivery-schedule-position-mandatory/buyer/receive#logistics-fields

[TC-7159] Improve delivery schedule position mandatory

---

api/environments.md

https://tradecloud.atlassian.net/browse/TC-7373
This PR fixes the production links to the YAML and Swagger UI on the environments page (.prod has been removed)

[TC-7373] Fix prod environment docs links

---

order/buyer/issue/README.md
order/buyer/receive/README.md
order/supplier/receive/README.md
order/supplier/send-order-response/README.md

https://tradecloud.atlassian.net/browse/TC-7729
This PR adds charge lines to 
- Send order by buyer
- Send order response by supplier
- Receive order by supplier
- Receive order response by buyer
- Adds `requests`, which was missing.

[TC-7729] Add charge lines

---

.gitbook/assets/tradecloud-demo.postman_collection.json

And reuse it in other requests
https://tradecloud.atlassian.net/browse/TC-8535
This PR updates the postman collection in the API v2 docs to include a "Test" script that will automatically set a `TcBearer` token based on the returned JWT token.
This env variable is then by default used in consecutive requests as bearer token.

fix: [TC-8535] Automatically set TcBearer env variable after login

---

order/buyer/receive/README.md
order/supplier/receive/README.md

https://tradecloud.atlassian.net/browse/TC-8375
Please review: https://app.gitbook.com/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/uAEcwmFuluqezQFGmw1G/
This PR removes the `The deliveryOverdue feature is planned` texts as this feature is released.
Note that `deliveryOverdue` on delivery line level not has been added to the webhook.
This may be added when migrating the webhook connector to Scala

[TC-8375] Remove `The deliveryOverdue feature is planned`

---

order/buyer/issue/README.md

https://tradecloud.atlassian.net/browse/TC-8500
This PR adds `transportMode` in the `deliverySchedule` in the buyer issue page
(The webhook `deliverySchedule` does not contain `status` and `transportMode`)
Please review https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/mHHEL3mpwVojLJ70A9rM/processes/order/buyer/issue#requested-planned-delivery-schedule

[TC-8500] Add transport mode

---

security/documents.md

https://tradecloud.atlassian.net/browse/TC-8676
This PR documents the list of file extensions that are blocked by the `object-storage`, as listing them in the API specs results in messy specs.

docs: [TC-8676] List blocked file extensions

---

api/rules.md
order/buyer/update.md

https://tradecloud.atlassian.net/browse/TC-8558
https://app.intercom.com/a/inbox/nel1ptj2/inbox/admin/2093215/conversation/106384000099046
https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/J1gG1glifd2ESGjTV4fI/processes/order/buyer/update
This PR makes the order update rule consistent: it is preferable, but not mandatory, to send only new or updated lines.

[TC-8558] Relax order update rule

---

order/buyer/receive/README.md
order/supplier/receive/README.md

https://tradecloud.atlassian.net/browse/TC-9132
This PR adds `deliveryScheduleIncludingRequests`, `prices` and `pricesIncludingRequests` on `lines` level.

[TC-9132] Add `prices` and `IncludingRequests`

---

api/webhook-vs-polling.md

https://tradecloud.atlassian.net/browse/TC-9408
https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/WoY9EC9u3vynV5K5XO0C/introduction/api/webhook-vs-polling#polling-usage
This PR renames the `lastUpdatedSince` filter to `lastUpdatedAfter`

 [TC-9408] Rename `lastUpdatedSince` filter to `lastUpdatedAfter`

---

SUMMARY.md
api/delivery-schedule.md
api/polling/README.md
api/polling/echo.md
api/rules.md
api/webhook-vs-polling.md
order/buyer/README.md
order/buyer/issue/README.md
order/buyer/receive/README.md
order/buyer/receive/simple-order-event.md
order/supplier/receive/README.md
order/supplier/receive/simple-order-event.md

https://tradecloud.atlassian.net/browse/TC-8713 In progress status story
https://tradecloud.atlassian.net/browse/TC-9481 Alert about Polling and "open" buyer reopen request in API docs. 
https://tradecloud.atlassian.net/browse/TC-9467 Alert about Polling and "open" buyer reopen request in API docs (superseded)
Please review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/nZCqdUTDMvvrpj07rcDN/
This PR 
- explains how to handle echoed changes in an open request when using polling
- replaces `lastUpdatedAt` by `lastUpdatedSince` (https://tradecloud.atlassian.net/browse/TC-9408)
- improves polling documentation by splitting up webhook versus polling and polling usage
- splits supplier API native and simple delivery schedule pages

[TC-8713] [TC-9481] [TC-9467] Explain how to handle open requests using polling

---

order/buyer/issue/indicators.md
order/buyer/issue/no-delivery-expected.md

https://tradecloud.atlassian.net/browse/TC-10065
review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/19dycTgZq3kS8CqpTg5m/processes/order/buyer/issue/indicators
other PRs
- https://github.com/tradecloud/tradecloud-connectors-scala/pull/1225
- https://github.com/tradecloud/tradecloud-docs-connectors/pull/8
This PR
- adds the reconfirmation request indicator
- adds the indicators behaviour when using the single delivery feature

[TC-10065] add reconfirmation request and single delivery indicators

---

api/delivery-schedule.md
api/json-vs-xml.md
api/requests.md
api/webhook-vs-polling.md

https://tradecloud.atlassian.net/browse/TC-10147
This PR updates the documentation to remove the mentions of the GET Order Webhook, and reword the usage of POST requests, to make this read more like it is the default.

docs: [TC-10147] Remove mentions of GET and reword usage of POST webhook

---

order/buyer/receive/README.md
order/buyer/receive/single-delivery-order-response.md
order/supplier/receive/README.md
order/supplier/receive/single-delivery-order.md

https://tradecloud.atlassian.net/browse/TC-10053
review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/NTiRiNqMmH7aC76DxTqO/
This PR ......
- re-adds order response endpoints (they were deleted at some point, and developers could not find them anymore)
- adds references to the order event names

[TC-10053] Add order response endpoints

---

order/buyer/issue/README.md
order/supplier/receive/README.md
order/supplier/send-order-response/README.md

https://tradecloud.atlassian.net/browse/TC-10243
review: https://app.gitbook.com/o/-LNyIUZSvpZWZ81yEr7V/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/otS0uDAU8rFonQHOw0z1/
This PR adds the optional item number to the buyer issue and supplier receive pages.
Also cleans up the supplier send order response page

[TC-10243] add optional item number
